version: '3'

volumes:
   myappdata:

networks:
  myappnet:

services:
  db:
    image: mysql:5.6.42
    container_name: myappdb
    ports:
      - "3308:3306"
    networks:
      - myappnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    volumes:
      - myappdata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    container_name: myappweb
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - myappnet
    depends_on:
      - db